# Generated by Django 4.0.4 on 2022-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_order_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Order Canceled', 'Order Canceled'), ('Order On the way', 'Order On the way'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing')], default='Order Received', max_length=100),
        ),
    ]
